// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ClientMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WS.Common {

  /// <summary>Holder for reflection information generated from ClientMessage.proto</summary>
  public static partial class ClientMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for ClientMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNDbGllbnRNZXNzYWdlLnByb3RvEglXUy5Db21tb24aGWdvb2dsZS9wcm90",
            "b2J1Zi9hbnkucHJvdG8aDkNvbW1vblBCLnByb3RvIm8KEVJlcXVlc3RNZXNz",
            "YWdlQW55Ei8KC3JlcWV1c3RUeXBlGAEgASgOMhouV1MuQ29tbW9uLkVudW1S",
            "ZXF1ZXN0VHlwZRIpCgtSZXF1ZXN0Qm9keRgCIAEoCzIULmdvb2dsZS5wcm90",
            "b2J1Zi5BbnkiNwoRUXVlcnlBY2NvdW50T3JkZXISDwoHb3JkZXJJZBgBIAEo",
            "CRIRCglBY2NvdW50SWQYAiABKAkiLAoJUXVlcnlGaWxsEg4KBkZpbGxJZBgB",
            "IAEoCRIPCgdBZ2VudElkGAIgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::WS.Common.CommonPBReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WS.Common.RequestMessageAny), global::WS.Common.RequestMessageAny.Parser, new[]{ "ReqeustType", "RequestBody" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WS.Common.QueryAccountOrder), global::WS.Common.QueryAccountOrder.Parser, new[]{ "OrderId", "AccountId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WS.Common.QueryFill), global::WS.Common.QueryFill.Parser, new[]{ "FillId", "AgentId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///响应消息
  /// </summary>
  public sealed partial class RequestMessageAny : pb::IMessage<RequestMessageAny> {
    private static readonly pb::MessageParser<RequestMessageAny> _parser = new pb::MessageParser<RequestMessageAny>(() => new RequestMessageAny());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestMessageAny> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WS.Common.ClientMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestMessageAny() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestMessageAny(RequestMessageAny other) : this() {
      reqeustType_ = other.reqeustType_;
      requestBody_ = other.requestBody_ != null ? other.requestBody_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestMessageAny Clone() {
      return new RequestMessageAny(this);
    }

    /// <summary>Field number for the "reqeustType" field.</summary>
    public const int ReqeustTypeFieldNumber = 1;
    private global::WS.Common.EnumRequestType reqeustType_ = global::WS.Common.EnumRequestType.None;
    /// <summary>
    ///请求消息类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WS.Common.EnumRequestType ReqeustType {
      get { return reqeustType_; }
      set {
        reqeustType_ = value;
      }
    }

    /// <summary>Field number for the "RequestBody" field.</summary>
    public const int RequestBodyFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any requestBody_;
    /// <summary>
    ///请求体数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any RequestBody {
      get { return requestBody_; }
      set {
        requestBody_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestMessageAny);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestMessageAny other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ReqeustType != other.ReqeustType) return false;
      if (!object.Equals(RequestBody, other.RequestBody)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ReqeustType != global::WS.Common.EnumRequestType.None) hash ^= ReqeustType.GetHashCode();
      if (requestBody_ != null) hash ^= RequestBody.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ReqeustType != global::WS.Common.EnumRequestType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ReqeustType);
      }
      if (requestBody_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RequestBody);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ReqeustType != global::WS.Common.EnumRequestType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReqeustType);
      }
      if (requestBody_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RequestBody);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestMessageAny other) {
      if (other == null) {
        return;
      }
      if (other.ReqeustType != global::WS.Common.EnumRequestType.None) {
        ReqeustType = other.ReqeustType;
      }
      if (other.requestBody_ != null) {
        if (requestBody_ == null) {
          RequestBody = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        RequestBody.MergeFrom(other.RequestBody);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ReqeustType = (global::WS.Common.EnumRequestType) input.ReadEnum();
            break;
          }
          case 18: {
            if (requestBody_ == null) {
              RequestBody = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(RequestBody);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///查询委托单
  /// </summary>
  public sealed partial class QueryAccountOrder : pb::IMessage<QueryAccountOrder> {
    private static readonly pb::MessageParser<QueryAccountOrder> _parser = new pb::MessageParser<QueryAccountOrder>(() => new QueryAccountOrder());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QueryAccountOrder> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WS.Common.ClientMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryAccountOrder() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryAccountOrder(QueryAccountOrder other) : this() {
      orderId_ = other.orderId_;
      accountId_ = other.accountId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryAccountOrder Clone() {
      return new QueryAccountOrder(this);
    }

    /// <summary>Field number for the "orderId" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private string orderId_ = "";
    /// <summary>
    ///委托单号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrderId {
      get { return orderId_; }
      set {
        orderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AccountId" field.</summary>
    public const int AccountIdFieldNumber = 2;
    private string accountId_ = "";
    /// <summary>
    ///利润中心id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QueryAccountOrder);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QueryAccountOrder other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderId != other.OrderId) return false;
      if (AccountId != other.AccountId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OrderId.Length != 0) hash ^= OrderId.GetHashCode();
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (OrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OrderId);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderId);
      }
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QueryAccountOrder other) {
      if (other == null) {
        return;
      }
      if (other.OrderId.Length != 0) {
        OrderId = other.OrderId;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrderId = input.ReadString();
            break;
          }
          case 18: {
            AccountId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///查询成交记录
  /// </summary>
  public sealed partial class QueryFill : pb::IMessage<QueryFill> {
    private static readonly pb::MessageParser<QueryFill> _parser = new pb::MessageParser<QueryFill>(() => new QueryFill());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QueryFill> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WS.Common.ClientMessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryFill() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryFill(QueryFill other) : this() {
      fillId_ = other.fillId_;
      agentId_ = other.agentId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QueryFill Clone() {
      return new QueryFill(this);
    }

    /// <summary>Field number for the "FillId" field.</summary>
    public const int FillIdFieldNumber = 1;
    private string fillId_ = "";
    /// <summary>
    ///成交记录id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FillId {
      get { return fillId_; }
      set {
        fillId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AgentId" field.</summary>
    public const int AgentIdFieldNumber = 2;
    private string agentId_ = "";
    /// <summary>
    ///资金账号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AgentId {
      get { return agentId_; }
      set {
        agentId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QueryFill);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QueryFill other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FillId != other.FillId) return false;
      if (AgentId != other.AgentId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FillId.Length != 0) hash ^= FillId.GetHashCode();
      if (AgentId.Length != 0) hash ^= AgentId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FillId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FillId);
      }
      if (AgentId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AgentId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FillId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FillId);
      }
      if (AgentId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AgentId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QueryFill other) {
      if (other == null) {
        return;
      }
      if (other.FillId.Length != 0) {
        FillId = other.FillId;
      }
      if (other.AgentId.Length != 0) {
        AgentId = other.AgentId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FillId = input.ReadString();
            break;
          }
          case 18: {
            AgentId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
