// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CommonPB.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WS.Common {

  /// <summary>Holder for reflection information generated from CommonPB.proto</summary>
  public static partial class CommonPBReflection {

    #region Descriptor
    /// <summary>File descriptor for CommonPB.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonPBReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Db21tb25QQi5wcm90bxIJV1MuQ29tbW9uKkAKD0VudW1SZXF1ZXN0VHlw",
            "ZRIICgROb25lEAASEAoMUXVlcnlGaWxsUmVxEAESEQoNUXVlcnlPcmRlclJl",
            "cRACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WS.Common.EnumRequestType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///请求类型
  /// </summary>
  public enum EnumRequestType {
    /// <summary>
    ///无
    /// </summary>
    [pbr::OriginalName("None")] None = 0,
    /// <summary>
    ///查询成交记录
    /// </summary>
    [pbr::OriginalName("QueryFillReq")] QueryFillReq = 1,
    /// <summary>
    ///查询委托单
    /// </summary>
    [pbr::OriginalName("QueryOrderReq")] QueryOrderReq = 2,
  }

  #endregion

}

#endregion Designer generated code
